### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [huykirbyLL/h-c-bailey_call-mr-fortune#2]
# General Issues:

- [x] There are several [Editorial] commits that should not be marked as such. The following are considered typography changes:

- [[Editorial] "3.30" to "3:30"](https://github.com/huykirbyLL/h-c-bailey_call-mr-fortune/commit/8cbec289e1146db678a57e6dc39a51f57ccd884c)
- [[Editorial] Change æ to ae](https://github.com/huykirbyLL/h-c-bailey_call-mr-fortune/commit/98dce33cd3336bcc28a1b6c7720c5ce0205a5392)
- [[Editorial] Change period to colon in hours](https://github.com/huykirbyLL/h-c-bailey_call-mr-fortune/commit/ab66a371ee404e826f702453801825fe936e5570)

You will need to do an interactive rebase to change the commit titles. If you need help with this process, feel free to ask!

# case-3.xhtml:

- [x] You can remove the single quotes inside the `<blockquote>`. Having double quotes, single quotes, and blockquote styling is redundant.

# case-6.xhtml:

- [x] You can remove the single quotes inside the `<blockquote epub:type="z3998:verse">`.

# colophon.xhtml:

- [x] Add an `<abbr>` element to `Call Mr. Fortune`.

**Comment by huykirbyLL** [comment]
Thanks Emma! I will make sure to avoid treating typography changes as editorial changes in the future. How do I do interactive rebase? I have never done it before so I would appreciate it if you can show me a good guide for that.

**Comment by EmmaSweeney** [comment]
To do an interactive rebase:

1. Run `git rebase -i HEAD~20`
2. To the left to each commit, will be the word `pick`. Change the word to `reword` in front of the commits you need to change.
3. Press ctrl + s then ctrl + x .
4. Next you will be able to change the messages one at a time. Remove `[Editorial]`.
5. After fixing each message, press ctrl + s then ctrl + x .
6. Repeat steps 4 and 5.
7. After the last message change, `git rebase` will automatically close.
8. To change your remote repository, run `git push --force-with-lease`.

Make sure to check your remote repository to see the changes. Let me know if you have any problems.

For more info, check out this GitHub page on [rebase](https://www.codecademy.com/resources/docs/git/rebase).

**Comment by huykirbyLL** [comment]
Hi Emma, is it normal to have duplicate commits after git push? I feel like I might have messed up something, so I wanted to ask just to be sure. Thanks.

Edit: I just checked via Github Desktop and "git log", and the history of my local repository seems fine, so the duplication only affects here.

**Comment by EmmaSweeney** [comment]
No, it isn't normal to have duplicate commits. If you look further in the respository history, the [Editorial] commits still exist.

Are you rebasing with Github Desktop or a command terminal?

**Comment by huykirbyLL** [comment]
I rebased following your steps using command terminal. However, when I did step "git push --force-with-lease", I thought it didn't go through so I resorted to Github Desktop. I think that's where it might have gone wrong. The duplicated commits seem like they are the the last 18 commits I made, except all the wrong "[Editorial]" commits have been replaced with the correct one.

My current local repository seems to have its commit history fixed. I checked via Github Desktop and "git log -20 --oneline", and it showed that there is no duplicated commit here and the wrong "[Editorial]" ones also got fixed.

Edit: I apologize for my carelessness. I checked further down the history of my local repository, and I found out that the duplicate commits are still there. How can I fix this?

**Comment by huykirbyLL** [comment]
I should clarify to be clearer: how do I undo my last 18 commits? Once I have done that, I can try to redo the interactive rebase steps that you gave me and see if "git push --force-with-lease" still causes problems. Thank you for your patience.

**Comment by EmmaSweeney** [comment]
Github Desktop doesn't play well with interactive rebase and will try to merge instead of overwrite.

What you need to do first is remove the latest commits. This can be done by using `drop` instead of `reword` in step two. Make sure to run `git push --force-with-lease`.  In a browser, check that the commits have been removed in your remote repository. If you see the changes, you can repeat the steps above. If you don't see the changes, you may need to use `git push --force`.

**Comment by huykirbyLL** [comment]
I have fixed the problem! My previous issue with "git push --force" happened because I didn't pass the authentication system. After looking up about "personal access tokens", I finally got the command to go through. This has been a good learning opportunity. Thanks for your instruction, Emma.
